### ISSUE TITLE
py-couchdb installation error in ubuntu12.04 with CouchDB 1.6.1 and python 2.7 as well as python 3.3

### ISSUE THREAD

**Issue by rkphilip45** [histrio/py-couchdb#62]
Dear Team,

I tried to install py-couchdb in ubuntu12.04 with CouchDB 1.6.1 and python 2.7 as well as python 3.3 and got the installation errors as given below:

$ pip install pycouchdb
Downloading/unpacking pycouchdb
  Downloading pycouchdb-1.13.tar.gz
  Running setup.py (path:/tmp/pip_build_otc/pycouchdb/setup.py) egg_info for package pycouchdb
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_otc/pycouchdb/setup.py", line 10, in <module>
        import pycouchdb
      File "pycouchdb/__init__.py", line 10, in <module>
        from .client import Server
      File "pycouchdb/client.py", line 13, in <module>
        from .resource import Resource
      File "pycouchdb/resource.py", line 5, in <module>
        import requests
    ImportError: No module named requests
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_otc/pycouchdb/setup.py", line 10, in <module>

    import pycouchdb

  File "pycouchdb/__init__.py", line 10, in <module>

    from .client import Server

  File "pycouchdb/client.py", line 13, in <module>

    from .resource import Resource

  File "pycouchdb/resource.py", line 5, in <module>

    import requests

ImportError: No module named requests

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_otc/pycouchdb
Storing debug log for failure in /tmp/tmpVI3k_S
$

Please advise.

Philip.

**Comment by histrio** [comment]
Hi @rkphilip45 
As a quick solution you can run `pip install requirements` before pycouch installation.

It's a bug of latest version which fixed now. 
Thanks!
