### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'history'

### ISSUE THREAD

**Issue by dhulke** [histrio/py-couchdb#71]
I have a web crawling app that creates a buffer of about 500 documents and bulk saves them to couch. Whenever I'm getting too many page errors, all of a sudden, for some unknown reason, this error pops up. I don't understand why page load errors would interfere with bulk save since I only buffer documents that have been correctly loaded. Any idea why this is happening?

Traceback (most recent call last):
  File "fetch.py", line 28, in <module>
    fetcher.fetch()
  File "C:\Users\danilo\Projects\CNPJReceita\cnpjreceita\fetcher.py", line 31, in fetch
    loop.run_until_complete(self.run())
  File "C:\Users\danilo\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\danilo\Projects\CNPJReceita\cnpjreceita\fetcher.py", line 43, in run
    await asyncio.gather(*all_jobs)
  File "C:\Users\danilo\Projects\CNPJReceita\cnpjreceita\fetcher.py", line 55, in cnpj_job
    self.flush()
  File "C:\Users\danilo\Projects\CNPJReceita\cnpjreceita\fetcher.py", line 63, in flush
    self.cnpjcouchdb.save_bulk(list(self.couch_buffer))
  File "C:\Users\danilo\Projects\CNPJReceita\cnpjreceita\cnpjcouchdb.py", line 25, in save_bulk
    return self.db.save_bulk(docs)
  File "C:\Users\danilo\Projects\CNPJReceita\venv\lib\site-packages\pycouchdb\client.py", line 403, in save_bulk
    _docs = copy.deepcopy(docs)
  File "C:\Users\danilo\AppData\Local\Programs\Python\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\danilo\AppData\Local\Programs\Python\Python36\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\danilo\AppData\Local\Programs\Python\Python36\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\danilo\AppData\Local\Programs\Python\Python36\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\danilo\AppData\Local\Programs\Python\Python36\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\danilo\AppData\Local\Programs\Python\Python36\lib\copy.py", line 274, in _reconstruct
    y = func(*args)
TypeError: __init__() missing 1 required positional argument: 'history'

**Comment by dhulke** [comment]
I haven't been able to find a consistent way to reproduce this error. Some times it happens very frequently and other times it doesn't happen at all for over a week. All I have are simple json objects I'm retrieving through aiohttp response.json(). Some of the text has weird characters, but that isn't consistently causing this error. I tried looking for the reduce functions which are getting called at `y = func(*args)` but I haven't found a single one that requires a history attribute.
Is there any other way we could try and find the cause for this without being able to consistently reproduce it?

**Comment by dhulke** [comment]
Or if we at least knew what function expects the history attribute we could probably infer what the error is

**Comment by histrio** [comment]
Thanks for the report, and apologies that this issue remained open for so long.

The failure occurred while `copy.deepcopy()` processed a non-standard object in the bulk document payload, but no minimal reproducible example was identified. The report also targets an unsupported Python 3.6 environment.

Since we cannot reproduce the issue on currently supported versions, I’m closing it for now. Please open a new issue with a minimal reproducer if this still occurs with pycouchdb 1.17.0 and Python 3.9 or later.

**Comment by dhulke** [comment]
8 years... Didn't take you too long. Don't worry about it. We literally had time to invent transformers, create gpt, then claude code and they were probably the ones to find this. Incredible haha.
